table DimCurso
	lineageTag: 8a8fcb23-b4e2-40dd-b2b9-3d3f88443ea4

	column cod_curso
		dataType: int64
		formatString: 0
		lineageTag: 78e494fc-f5fd-4aa8-a940-0f35f9253a9e
		summarizeBy: none
		sourceColumn: cod_curso

		annotation SummarizationSetBy = Automatic

	column nome_curso
		dataType: string
		lineageTag: deb65225-0fbe-4533-9dca-ad544402074c
		summarizeBy: none
		sourceColumn: nome_curso

		annotation SummarizationSetBy = Automatic

	column carga_horaria
		dataType: int64
		formatString: 0
		lineageTag: a76d97b8-c32b-4e89-be95-2b16526559ed
		summarizeBy: none
		sourceColumn: carga_horaria

		annotation SummarizationSetBy = Automatic

	partition DimCurso = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\thorc\Downloads\amostra_evg (1).csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"cod_curso", "nome_curso", "carga_horaria"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"cod_curso"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

