table DimConteudista
	lineageTag: 7964d12e-8ad5-4482-a19d-7d9a7cce91ec

	column codigo_conteudista
		dataType: int64
		formatString: 0
		lineageTag: e82f934f-1e66-448a-8584-9300f1016bcb
		summarizeBy: none
		sourceColumn: codigo_conteudista

		annotation SummarizationSetBy = Automatic

	column email_conteudista
		dataType: string
		lineageTag: 4b0bf49d-47ea-4ea7-959e-49e6154b54da
		summarizeBy: none
		sourceColumn: email_conteudista

		annotation SummarizationSetBy = Automatic

	column conteudista
		dataType: string
		lineageTag: d2e8acf1-b95c-41fe-89a2-af4116006303
		summarizeBy: none
		sourceColumn: conteudista

		annotation SummarizationSetBy = Automatic

	partition DimConteudista = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\thorc\Downloads\amostra_evg (1).csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"email_conteudista", "conteudista"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Duplicatas Removidas", "Índice", 1, 1, Int64.Type),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Índice Adicionado",{"Índice", "email_conteudista", "conteudista"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Reordenadas",{{"Índice", "codigo_conteudista"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

