table DimInstituicao
	lineageTag: d9ac9536-d3d2-49be-b585-5fe090f16e91

	column codigo_instituicao
		dataType: int64
		formatString: 0
		lineageTag: 0caf6864-e7c1-4a27-a547-9ecb2081abdf
		summarizeBy: none
		sourceColumn: codigo_instituicao

		annotation SummarizationSetBy = Automatic

	column instituicao
		dataType: string
		lineageTag: 41791a95-d8f9-4a19-9cec-2ef2e351ca0b
		summarizeBy: none
		sourceColumn: instituicao

		annotation SummarizationSetBy = Automatic

	partition DimInstituicao = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\thorc\Downloads\amostra_evg (1).csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"instituicao"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Erros Removidos" = Table.RemoveRowsWithErrors(#"Duplicatas Removidas", {"instituicao"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Erros Removidos", each [instituicao] <> null and [instituicao] <> ""),
				    #"Índice Adicionado" = Table.AddIndexColumn(#"Linhas Filtradas", "Índice", 1, 1, Int64.Type),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Índice Adicionado",{"Índice", "instituicao"}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Colunas Reordenadas",{{"Índice", "codigo_instituicao"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

