table DimPessoa
	lineageTag: 561619bd-aa2b-46c8-80f6-286180ff8d02

	column codigo_pessoa
		dataType: string
		lineageTag: 6856838e-0719-46d7-ba20-4bf81abad4e1
		summarizeBy: none
		sourceColumn: codigo_pessoa

		annotation SummarizationSetBy = Automatic

	column sexo
		dataType: string
		lineageTag: be25a122-7a8d-4c99-a0ee-b6aac5788467
		summarizeBy: none
		sourceColumn: sexo

		annotation SummarizationSetBy = Automatic

	column idade
		dataType: int64
		formatString: 0
		lineageTag: 3ab35e7b-0d38-4822-bb20-70199b9b15dd
		summarizeBy: none
		sourceColumn: idade

		annotation SummarizationSetBy = Automatic

	column email_pessoa
		dataType: string
		lineageTag: 140ad0e7-8657-4cd3-bd91-e85e8bc2c7af
		summarizeBy: none
		sourceColumn: email_pessoa

		annotation SummarizationSetBy = Automatic

	column telefone_pessoa
		dataType: int64
		formatString: 0
		lineageTag: adb6587c-6805-4209-b753-c35a7fb78a15
		summarizeBy: none
		sourceColumn: telefone_pessoa

		annotation SummarizationSetBy = Automatic

	column nacionalidade
		dataType: string
		lineageTag: 652c845a-c850-4053-bee9-e4a81b1d099c
		summarizeBy: none
		sourceColumn: nacionalidade

		annotation SummarizationSetBy = Automatic

	partition DimPessoa = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\thorc\Downloads\amostra_evg (1).csv"),[Delimiter=",", Columns=25, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"cod_matricula", type text}, {"dt_matricula", type datetime}, {"nacionalidade", type text}, {"cod_turma", Int64.Type}, {"nome_turma", type text}, {"modalidade_turma", type text}, {"cod_curso", Int64.Type}, {"nome_curso", type text}, {"carga_horaria", Int64.Type}, {"dt_fim", type datetime}, {"sit_turma", type text}, {"instituicao", type text}, {"municipio_pessoa", type text}, {"uf_pessoa", type text}, {"conteudista", type text}, {"tematica", type text}, {"codigo_pessoa", type text}, {"sexo", type text}, {"idade", Int64.Type}, {"sit_matricula", type text}, {"poder", type text}, {"esfera", type text}, {"email_pessoa", type text}, {"telefone_pessoa", Int64.Type}, {"email_conteudista", type text}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Tipo Alterado",{"codigo_pessoa", "sexo", "idade", "email_pessoa", "telefone_pessoa", "nacionalidade"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas", {"codigo_pessoa"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

